# Generated by Django 5.1.4 on 2024-12-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('dateOfCreation', models.DateTimeField(auto_now=True)),
                ('dateOfUpdate', models.DateTimeField()),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
    ]
