# Generated by Django 5.1.4 on 2024-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateOfUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
